### PR TITLE
expose key, owner, peers

### PR DESCRIPTION
**Pull request by joehand**
#32, #33, #34 

cc @juliangruber

### CODE REVIEW

**Comment by juliangruber** [comment]
👍 

Do we want to add tests for this as well?

**Comment by juliangruber** [comment]
adding tests

**Comment by juliangruber** [comment]
@joehand can you look at the added commits?

**Comment by juliangruber** [comment]
meh, the tests for .stats.peers are flaky. shall we just test if the events are fired?

**Comment by joehand** [comment]
> meh, the tests for .stats.peers are flaky. shall we just test if the events are fired?

Ya, removed the ones for >1 peer. We should be testing the connection counts in the swarm module anyways.

**Pull request merged**
